[project]
name = "10-hour-video"
version = "0.1.0"
description = "Download YouTube videos and create extended looped versions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yt-dlp>=2024.0.0",
    "moviepy>=2.0.0",
]
